import type { Character } from "./types";

export const characters: Character[] = [
  {
    slug: "posipaky",
    name_ua: "Посіпаки",
    short_ua: "Яскрава парна анімація з гумором, рухливими іграми та веселими челенджами.",
    description_ua:
      "Посіпаки у парі створюють максимально драйвову атмосферу: інтерактивні конкурси, музичні активності, естафети та багато сміху для дітей різного віку.",
    age_range_ua: "4-10 років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2500,
    tags_ua: ["пара персонажів", "мультгерої", "активні ігри", "весела вечірка"],
    hero_image: { src: "/images/characters/posipaky/hero.jpg", alt: "Посіпаки" },
    images: [{ src: "/images/characters/posipaky/hero.jpg", alt: "Посіпаки на святі" }],
    is_featured: true,
  },
  {
    slug: "anna-ta-elza",
    name_ua: "Анна та Ельза",
    short_ua: "Казковий дует принцес для ніжного й чарівного дитячого свята.",
    description_ua:
      "Анна та Ельза проводять програму у форматі казкової пригоди: танцювальні паузи, тематичні ігри та святкові активності з атмосферою королівства.",
    age_range_ua: "3-9 років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2600,
    tags_ua: ["принцеси", "казкова програма", "пара персонажів", "Frozen"],
    hero_image: { src: "/images/characters/anna-ta-elza/hero-v2.jpg", alt: "Анна та Ельза зі сніжинками" },
    images: [{ src: "/images/characters/anna-ta-elza/photo-v2.jpg", alt: "Анна та Ельза з тематичним реквізитом" }],
    is_featured: true,
  },
  {
    slug: "yedynorizhka-ta-veselka",
    name_ua: "Єдиноріжка та Веселка",
    short_ua: "Кольорова святкова пара з фантазійними іграми, танцями та яскравими емоціями.",
    description_ua:
      "Єдиноріжка та Веселка дарують wow-настрій: креативні завдання, командні активності, музичні конкурси та багато святкового кольору.",
    age_range_ua: "4-10 років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2500,
    tags_ua: ["єдиноріжка", "веселка", "яскрава вечірка", "пара персонажів"],
    hero_image: { src: "/images/characters/yedynorizhka-ta-veselka/hero.jpg", alt: "Єдиноріжка та Веселка" },
    images: [
      {
        src: "/images/characters/yedynorizhka-ta-veselka/hero.jpg",
        alt: "Єдиноріжка та Веселка на святі",
      },
    ],
    is_featured: true,
  },
  {
    slug: "skai-ta-honshchyk",
    name_ua: "Скай та Гонщик",
    short_ua: "Рятувальна парна анімація з командними місіями та тематичними іграми.",
    description_ua:
      "Скай та Гонщик проводять активну програму у стилі рятувальної команди: естафети, інтерактивні завдання та веселі місії для дітей.",
    age_range_ua: "3-8 років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2500,
    tags_ua: ["щенячий патруль", "рятувальна місія", "мультгерої", "пара персонажів"],
    hero_image: { src: "/images/characters/skai-ta-honshchyk/hero.jpg", alt: "Скай та Гонщик" },
    images: [{ src: "/images/characters/skai-ta-honshchyk/hero.jpg", alt: "Скай та Гонщик на святі" }],
    is_featured: true,
  },
  {
    slug: "rumi-ta-mira",
    name_ua: "Румі та Міра",
    short_ua: "Стильний дует для старших дітей: музика, танці, конкурси та сучасний вайб.",
    description_ua:
      "Румі та Міра ведуть трендову програму для тінейджерів: батли, творчі завдання, музичні активності та командні челенджі.",
    age_range_ua: "8-14 років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2700,
    tags_ua: ["k-pop", "тінейджери", "танцювальна програма", "пара персонажів"],
    hero_image: { src: "/images/characters/rumi-ta-mira/hero.jpg", alt: "Румі та Міра" },
    images: [{ src: "/images/characters/rumi-ta-mira/hero.jpg", alt: "Румі та Міра на святі" }],
    is_featured: true,
  },
  {
    slug: "venzdei-ta-enit",
    name_ua: "Венздей та Еніт",
    short_ua: "Контрастна пара героїнь для атмосферної вечірки у стилі Невермор.",
    description_ua:
      "Венздей та Еніт створюють яскравий мікс настроїв: містична атмосфера, командні завдання та багато інтерактиву для дітей, які люблять стильні тематичні свята.",
    age_range_ua: "5+ років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2800,
    tags_ua: ["Невермор", "Венздей", "Еніт", "пара персонажів", "тематична вечірка"],
    hero_image: { src: "/images/characters/venzdei-ta-enit/hero.jpg", alt: "Венздей та Еніт" },
    images: [{ src: "/images/characters/venzdei-ta-enit/hero.jpg", alt: "Венздей та Еніт на святі" }],
    is_featured: true,
  },
  {
    slug: "betgerl-ta-supervumen",
    name_ua: "Бетгерл та супервумен",
    short_ua: "Супергеройський дует для місій, випробувань та рятувальних пригод.",
    description_ua:
      "Бетгерл та супервумен проводять динамічну програму з місіями на силу, влучність і командну роботу. Ідеально для дітей, які люблять героїчні сюжети.",
    age_range_ua: "5+ років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2800,
    tags_ua: ["супергерої", "Бетгерл", "супервумен", "пара персонажів", "місії"],
    hero_image: { src: "/images/characters/betgerl-ta-supervumen/hero.jpg", alt: "Бетгерл та супервумен" },
    images: [{ src: "/images/characters/betgerl-ta-supervumen/hero.jpg", alt: "Супергеройський дует на святі" }],
    is_featured: true,
  },
  {
    slug: "kachechka-ta-trol-rozochka",
    name_ua: "Качечка та троль Розочка",
    short_ua: "Добра й весела пара для наймолодших гостей і яскравої вечірки.",
    description_ua:
      "Качечка та троль Розочка обожнюють гучні вечірки, танці та обійми. Ця пара чудово підходить для дитячих свят з м'якою, дружньою атмосферою.",
    age_range_ua: "3+ років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2600,
    tags_ua: ["Качечка", "троль Розочка", "дитяча вечірка", "танці", "пара персонажів"],
    hero_image: { src: "/images/characters/kachechka-ta-trol-rozochka/hero.jpg", alt: "Качечка та троль Розочка" },
    images: [{ src: "/images/characters/kachechka-ta-trol-rozochka/hero.jpg", alt: "Качечка та троль Розочка на святі" }],
    is_featured: true,
  },
  {
    slug: "barbi-ta-pryntsesa",
    name_ua: "Барбі та Принцеса",
    short_ua: "Казковий дует для гламурної вечірки з танцями, конкурсами та wow-настроєм.",
    description_ua:
      "Барбі та Принцеса проводять святкову програму з елементами казки, б'юті-активностями та творчими завданнями. Ідеально для дівочих вечірок.",
    age_range_ua: "5+ років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2800,
    tags_ua: ["Барбі", "Принцеса", "казковий світ", "дівоча вечірка", "пара персонажів"],
    hero_image: { src: "/images/characters/barbi-ta-pryntsesa/hero.jpg", alt: "Барбі та Принцеса" },
    images: [{ src: "/images/characters/barbi-ta-pryntsesa/photo-2.jpg", alt: "Образ Барбі на святі" }],
    is_featured: true,
  },
  {
    slug: "futbolni-veduchi",
    name_ua: "Футбольні ведучі",
    short_ua: "Спортивна пара ведучих для активної футбольної програми.",
    description_ua:
      "Двоє ведучих у футбольному стилі проводять рухливі естафети, командні завдання та спортивні челенджі для активних дітей.",
    age_range_ua: "5+ років",
    duration_options_minutes: [60, 90, 120],
    base_price_uah_from: 2700,
    tags_ua: ["футбол", "спорт", "2 ведучих", "командні ігри", "активні програми"],
    hero_image: { src: "/images/characters/futbolni-veduchi/hero.jpg", alt: "Футбольні ведучі" },
    images: [{ src: "/images/characters/futbolni-veduchi/hero.jpg", alt: "Футбольні ведучі на святі" }],
    is_featured: true,
  },
];
